### ISSUE TITLE
Some initial feedback/questions

### ISSUE THREAD

**Issue by webpro** [juancarlosjr97/release-it-containerized#16]
This is awesome! I'll definitely link to it from the release-it readme.

Without actually trying it out yet, a few questions:

- Maybe the `command: "--ci"` looks a tad odd maybe, also while knowing the `--ci` flag is already the default mode for release-it (or perhaps you could set `CI=1` in the container if it isn't?)
- Some people want to publish to the npm registry in the release process, but struggle to get npm config right in their Action. Can users already `npm publish` with yours, or is that a planned feature?
- Not sure if possible, but would be very convenient to not need to provide the list of plugins, but to derive them automatically from the release-it config (the keys of the `plugins` object).

**Comment by juancarlosjr97** [comment]
Thank you @webpro :) 

* I did not know it was the default command! Yes, it does make sense to set it to an empty string and fallback to the default from release-it which is the whole idea!
* I was actually doing this last night as I need to use it on GitLab with a custom registry for npm... Long story short, yes, it is possible right now to pass the `.npmrc` file or an environmental variable in the compatible structure to be picked up by NPM (https://docs.npmjs.com/cli/v6/using-npm/config#npmrc-files). Perhaps, to make it easier a specific path or configuration, I need to think about it a little bit more. I will raise a ticket for the change.
* Yes, that is totally possible and I like it very much the idea, and then set it to the latest version if not plugin list with the version is set.

**Comment by juancarlosjr97** [comment]
Thank you for the initial feedback @webpro :) 

I am going to close this issue and then we can focus on each topic on each respective issue.

**Comment by webpro** [comment]
Just saying, added to the release-it docs here: https://github.com/release-it/release-it?tab=readme-ov-file#containerized
